// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIUOaVDvGZmhm1hweEPIHI2v_WfRhVP7o',
    appId: '1:746800149870:web:4886cca4c84ca97b3afd7f',
    messagingSenderId: '746800149870',
    projectId: 'attendance-dpmptsp',
    authDomain: 'attendance-dpmptsp.firebaseapp.com',
    storageBucket: 'attendance-dpmptsp.firebasestorage.app',
    measurementId: 'G-CBJH2Z2C54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMwEtf5EwJY2d-aLO0D0QdhR6JlmFxtMY',
    appId: '1:746800149870:android:7035e2db35d559ef3afd7f',
    messagingSenderId: '746800149870',
    projectId: 'attendance-dpmptsp',
    storageBucket: 'attendance-dpmptsp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNA8pkgFlRQI9qA5sWB_A93TY4VuDMZjI',
    appId: '1:746800149870:ios:ac7fc8e328e68bac3afd7f',
    messagingSenderId: '746800149870',
    projectId: 'attendance-dpmptsp',
    storageBucket: 'attendance-dpmptsp.firebasestorage.app',
    iosBundleId: 'id.go.surabaya.dpmptsp.absensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNA8pkgFlRQI9qA5sWB_A93TY4VuDMZjI',
    appId: '1:746800149870:ios:ac7fc8e328e68bac3afd7f',
    messagingSenderId: '746800149870',
    projectId: 'attendance-dpmptsp',
    storageBucket: 'attendance-dpmptsp.firebasestorage.app',
    iosBundleId: 'id.go.surabaya.dpmptsp.absensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIUOaVDvGZmhm1hweEPIHI2v_WfRhVP7o',
    appId: '1:746800149870:web:b619fd6604a2ef783afd7f',
    messagingSenderId: '746800149870',
    projectId: 'attendance-dpmptsp',
    authDomain: 'attendance-dpmptsp.firebaseapp.com',
    storageBucket: 'attendance-dpmptsp.firebasestorage.app',
    measurementId: 'G-6DZZM4ZRX0',
  );
}
